version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      groups:
          react:
              patterns:
                  - "react"
                  - "react-dom"
                  - "@types/react"
                  - "@types/react-dom"
          vite:
              patterns:
                  - "vite"
                  - "@vitejs/*"
          eslint:
              patterns:
                  - "eslint"
                  - "eslint-*"
                  - "@typescript-eslint/*"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
